### ISSUE TITLE
Error when trying to 'run with colt'

### ISSUE THREAD

**Issue by webuniverseio** [code-orchestra/colt-sublime3-plugin#2]
Error when trying to 'run with colt':

```
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'codeOrchestra.colt.js.session.sourcetracking.ResourceFile@3cfbc0' with class 'codeOrchestra.colt.js.session.sourcetracking.ResourceFile' to class 'codeOrchestra.colt.js.session.sourcetracking.HTMLSourceFile'
    at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:371)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.castToType(ScriptBytecodeAdapter.java:599)
    at codeOrchestra.colt.js.controller.StartLiveTask.applyHtmlTransformation(StartLiveTask.groovy:244)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:361)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
    at codeOrchestra.colt.js.controller.StartLiveTask$_call_closure1.doCall(StartLiveTask.groovy:118)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
    at groovy.lang.Closure.call(Closure.java:423)
    at groovy.lang.Closure.call(Closure.java:439)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1324)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1296)
    at org.codehaus.groovy.runtime.dgm$147.invoke(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at codeOrchestra.colt.js.controller.StartLiveTask.call(StartLiveTask.groovy:117)
    at codeOrchestra.colt.js.controller.StartLiveTask.call(StartLiveTask.groovy)
    at codeOrchestra.colt.core.tasks.ColtTaskWithProgress.call(ColtTaskWithProgress.java:25)
    at javafx.concurrent.Task$TaskCallable.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

```

**Comment by webuniverseio** [comment]
Does anyone else experience the issue? It happens in sublime text 3 when I'm trying to connect COLT with my code by pressing 'run with colt'. Am I doing something wrong?

**Comment by makc** [comment]
[С наступающим!](https://twitter.com/potapenko_ru/status/415894455208919040)

**Comment by webuniverseio** [comment]
@makc Happy new year and merry christmas! :)

**Comment by prplx** [comment]
The root of trouble is double backslashes in ST paths in Windows. If you run this command in the ST console: window.active_view().file_name() (the plugin uses this ST function for getting active document's path), in Mac OS X you'll get something like this: /Users/user/Documents/test/index.html. But if you use ST in Windows, you'll get something like this: D:\\Projects\\Test\\index.html. This path exports to Main Document field in COLT that is not acceptable for it, and COLT is going down. 

PS. Sorry for my English.

**Comment by makc** [comment]
@mmystiq this information will be helpful if correct, thanks!
