### ISSUE TITLE
Getting exception when trying to 'Show value in console'

### ISSUE THREAD

**Issue by webuniverseio** [code-orchestra/colt-sublime3-plugin#6]
When I'm running 'Show value in console' for window.outerWidth I'm getting right number in output, but when I switch to sublime text console (ctrl + `) I'm seeing following exception:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
  File "run_with_colt in C:\Program Files\Sublime Text 3\Data\Installed Packages\COLT.sublime-package", line 240, in run
AttributeError: 'AppendToConsoleCommand' object has no attribute 'size'
```

**Comment by makc** [comment]
This was probably a typo. Please reinstall the plugin, and reopen if there is still a problem, we'll look into it on monday.

**Comment by webuniverseio** [comment]
Seems to be fixed, thank you.
